<?php

namespace ContainerINEsPxM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TjHjE3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tjHjE3_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tjHjE3_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthorController::Affiche' => ['privates', '.service_locator.4HiMcib', 'get_ServiceLocator_4HiMcibService', true],
            'App\\Controller\\AuthorController::addStatistique' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AuthorController::delete' => ['privates', '.service_locator.4HiMcib', 'get_ServiceLocator_4HiMcibService', true],
            'App\\Controller\\AuthorController::edit' => ['privates', '.service_locator.4HiMcib', 'get_ServiceLocator_4HiMcibService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AuthorController:Affiche' => ['privates', '.service_locator.4HiMcib', 'get_ServiceLocator_4HiMcibService', true],
            'App\\Controller\\AuthorController:addStatistique' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AuthorController:delete' => ['privates', '.service_locator.4HiMcib', 'get_ServiceLocator_4HiMcibService', true],
            'App\\Controller\\AuthorController:edit' => ['privates', '.service_locator.4HiMcib', 'get_ServiceLocator_4HiMcibService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AuthorController::Affiche' => '?',
            'App\\Controller\\AuthorController::addStatistique' => '?',
            'App\\Controller\\AuthorController::delete' => '?',
            'App\\Controller\\AuthorController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthorController:Affiche' => '?',
            'App\\Controller\\AuthorController:addStatistique' => '?',
            'App\\Controller\\AuthorController:delete' => '?',
            'App\\Controller\\AuthorController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
