<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerINEsPxM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerINEsPxM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerINEsPxM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerINEsPxM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerINEsPxM\App_KernelDevDebugContainer([
    'container.build_hash' => 'INEsPxM',
    'container.build_id' => '4e624618',
    'container.build_time' => 1697671181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerINEsPxM');
